=== ansforge/SAMU-Hub-Modeles/src/main/resources/json-schema/EDXL-DE-envelope-only.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://json-schema.org/draft-07/schema#",
  "required": [
    "senderID",
    "distributionID",
    "dateTimeSent",
    "dateTimeExpires",
    "distributionStatus",
    "distributionKind",
    "descriptor",
    "content"
  ],
  "properties": {
    "senderID": {
      "type": "string"
    },
    "distributionID": {
      "type": "string"
    },
    "dateTimeSent": {
      "type": "string",
      "format": "date-time"
    },
    "dateTimeExpires": {
      "type": "string",
      "format": "date-time"
    },
    "content": {
      "$ref": "#/definitions/Content"
    },
    "descriptor": {
      "$ref": "#/definitions/Descriptor"
    },
    "distributionKind": {
      "$ref": "#/definitions/DistributionKind"
    },
    "distributionStatus": {
      "$ref": "#/definitions/DistributionStatus"
    }
  },
  "additionalProperties": false,
  "definitions": {
    "Content": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ContentObject"
      },
      "minItems": 1
    },
    "ContentObject": {
      "type": "object",
      "required": [
        "jsonContent"
      ],
      "properties": {
        "jsonContent": {
          "$ref": "#/definitions/JsonContent"
        }
      },
      "additionalProperties": false
    },
    "JsonContent": {
      "type": "object",
      "required": [
        "embeddedJsonContent"
      ],
      "properties": {
        "embeddedJsonContent": {
          "$ref": "#/definitions/EmbeddedJsonContent"
        }
      },
      "additionalProperties": false
    },
    "EmbeddedJsonContent": {
      "type": "object"
    },
    "Descriptor": {
      "type": "object",
      "properties": {
        "explicitAddress": {
          "$ref": "#/definitions/ExplicitAddress"
        },
        "language": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "explicitAddress",
        "language"
      ]
    },
    "DistributionKind": {
      "type": "string",
      "enum": [
        "Report",
        "Update",
        "Cancel",
        "Ack",
        "Error"
      ]
    },
    "DistributionStatus": {
      "type": "string",
      "enum": [
        "Actual",
        "Exercise"
      ]
    },
    "ExplicitAddress": {
      "type": "object",
      "properties": {
        "explicitAddressScheme": {
          "type": "string"
        },
        "explicitAddressValue": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "explicitAddressScheme",
        "explicitAddressValue"
      ]
    }
  }
}

=== ansforge/SAMU-Hub-Modeles/src/main/resources/sample/valid/new-RC-EDA/new-RC-EDA.json
{
  "distributionID": "fr.health.samuA_2608323d-507d-4cbf-bf74-52007f8124ea",
  "senderID": "fr.health.samuA",
  "dateTimeSent": "2022-07-25T10:04:34+01:00",
  "dateTimeExpires": "2072-07-25T10:04:34+01:00",
  "distributionStatus": "Actual",
  "distributionKind": "Report",
  "descriptor": {
    "language": "fr-FR",
    "explicitAddress": {
      "explicitAddressScheme": "hubex",
      "explicitAddressValue": "fr.health.samuB"
    }
  },
  "content": [
    {
      "jsonContent": {
        "embeddedJsonContent": {
          "message": {
            "messageId": "fr.health.samuA_2608323d-507d-4cbf-bf74-52007f8124ea",
            "sender": {
              "name": "samuA",
              "URI": "hubex:fr.health.samuA"
            },
            "sentAt": "2022-07-25T10:04:34+01:00",
            "kind": "Report",
            "status": "Actual",
            "recipients": [
              {
                "name": "samuB",
                "URI": "hubex:fr.health.samuB"
              }
            ],
            "createCase": {
              "caseId": "samuA:CA126B445579GD4A67AV",
              "senderCaseId": "CA126B445579GD4A67AV",
              "creation": "2022-09-27T08:23:34+02:00",
              "referenceVersion": "1.2",
              "qualification": {
                "whatsHappen": {
                  "code": "C07.13.02",
                  "label": "Rod\u00e9o automobile",
                  "freetext": "None"
                },
                "locationKind": {
                  "code": "TO_BE_CONTROLLED",
                  "label": "TO_BE_CONTROLLED",
                  "freetext": "TO_BE_CONTROLLED"
                },
                "riskThreat": [
                  {
                    "code": "TO_BE_CONTROLLED",
                    "label": "TO_BE_CONTROLLED",
                    "freetext": "TO_BE_CONTROLLED"
                  },
                  {
                    "code": "TO_BE_CONTROLLED",
                    "label": "TO_BE_CONTROLLED",
                    "freetext": "TO_BE_CONTROLLED"
                  }
                ],
                "healthMotive": {
                  "code": "TO_BE_CONTROLLED",
                  "label": "TO_BE_CONTROLLED",
                  "freetext": "TO_BE_CONTROLLED"
                },
                "victims": {
                  "count": "SEVERAL",
                  "mainVictim": "CHILD",
                  "freetext": "Jeanne Dupont, 6 ans, ne r\u00e9pond plus"
                }
              },
              "location": {
                "locID": "111fb03a-6fd9-41e0-8e81-990c45188887",
                "locLabel": "Lyc\u00e9e Pierre de Coubertin - 12 rue de l'Amiti\u00e9 77288 Melun, Mus\u00e9e Bossuet - Acc\u00e8s 2 - 77048 Saint-Albray",
                "name": "Lyc\u00e9e Pierre de Coubertin",
                "detailedAdress": {
                  "complete": "9 Bd du Montparnasse",
                  "number": "9, 4bis, PK10, \u2026",
                  "wayName": {
                    "complete": "Boulevard du Montparnasse",
                    "type": "Boulevard",
                    "name": "du Montparnasse"
                  }
                },
                "city": {
                  "name": "Lille",
                  "inseeCode": 59350,
                  "detail": "Quartie Melun Nord, Lhomme, \u2026"
                },
                "access": {
                  "floor": "RDC, 1, 2, \u2026",
                  "roomNumber": "A16, 37, 104, \u2026",
                  "interphone": "Dupont",
                  "accessCode": [
                    "1234A",
                    "4321B"
                  ],
                  "elevator": "C3",
                  "buildingName": "Batiment B, Batiment Maunoury",
                  "entrance": "Zone Sud, Porte 1, \u2026",
                  "entity": "Infirmerie, service finance, service cardiologie, \u2026"
                },
                "geometry": {
                  "obsDatime": "2022-09-27T08:23:34+02:00",
                  "point": {
                    "coord": {
                      "lat": 48.866667,
                      "lon": 2.333333,
                      "height": 120,
                      "heading": 96,
                      "speed": 34,
                      "precision": "ADDRESS"
                    },
                    "sysCoord": "EPSG-4326"
                  },
                  "sketch": "None"
                },
                "externalInfo": [
                  {
                    "freetext": "BAN",
                    "type": "MANUAL",
                    "uri": "id987"
                  }
                ],
                "country": "FR",
                "freetext": "Cl\u00e9 derri\u00e8re le pot de fleur"
              },
              "initialAlert": {
                "id": "SGO050-20230605-AL0123",
                "reception": "2022-09-27T08:21:06+02:00",
                "reporting": "STANDARD",
                "freetext": "D\u00e9clenchement t\u00e9l\u00e9alarme, voisine sur les liens",
                "caller": {
                  "callerContact": {
                    "type": "PHNADD",
                    "detail": "0671830530"
                  },
                  "callbackContact": {},
                  "language": "FR",
                  "freetext": "P\u00e8re",
                  "detailedName": {
                    "complete": "Jean Dupont",
                    "lastName": "Dupont",
                    "firstName": "Jean"
                  }
                },
                "alertSource": {
                  "channel": "Personne",
                  "type": "PHNADD",
                  "detail": "0671830530"
                },
                "location": {},
                "qualification": {},
                "callTaker": {
                  "organization": "FR:Administration:44:samu44:crra:regulationN3",
                  "controlRoom": "CGA, CGO 21, CRRA 44, ...",
                  "role": "ARM",
                  "calltakeContact": {},
                  "calltakerId": "id1234"
                },
                "attachment": [
                  {
                    "description": "photo, carte, \u2026",
                    "mimeType": "PDF, XML, JPEG, \u2026",
                    "size": 1235,
                    "URI": "https://hub.esante.gouv.fr/resourceExample",
                    "derefURI": "None",
                    "digest": "None"
                  }
                ]
              },
              "newAlert": [
                {}
              ],
              "additionalInformation": {
                "customMap": {
                  "key": "neighborhood",
                  "label": "Quartier",
                  "value": "LYON 2e arrondissement",
                  "freetext": "Pr\u00e9cision sur le quartier d'intervention"
                }
              },
              "freetext": "None"
            }
          }
        }
      }
    }
  ]
}

=== ansforge/SAMU-Hub-Modeles/src/main/resources/sample/valid/RC-EDA/RC-EDA.json
{
  "distributionID": "fr.health.samuA_2608323d-507d-4cbf-bf74-52007f8124ea",
  "senderID": "fr.health.samuA",
  "dateTimeSent": "2022-07-25T10:04:34+01:00",
  "dateTimeExpires": "2072-07-25T10:04:34+01:00",
  "distributionStatus": "Actual",
  "distributionKind": "Report",
  "descriptor": {
    "language": "fr-FR",
    "explicitAddress": {
      "explicitAddressScheme": "hubex",
      "explicitAddressValue": "fr.health.samuB"
    }
  },
  "content": [
    {
      "jsonContent": {
        "embeddedJsonContent": {
          "message": {
            "messageId": "fr.health.samuA_2608323d-507d-4cbf-bf74-52007f8124ea",
            "sender": {
              "name": "samuA",
              "URI": "hubex:fr.health.samuA"
            },
            "sentAt": "2022-07-25T10:04:34+01:00",
            "kind": "Report",
            "status": "Actual",
            "recipient": [
              {
                "name": "samuB",
                "URI": "hubex:fr.health.samuB"
              }
            ],
            "createCase": {
              "caseId": "samuA:CA126B445579GD4A67AV",
              "senderCaseId": "CA126B445579GD4A67AV",
              "creation": "2022-09-27T08:23:34+02:00",
              "referenceVersion": "1.2",
              "qualification": {
                "whatsHappen": {
                  "code": "C07.13.02",
                  "label": "Rod\u00e9o automobile",
                  "freetext": "None"
                },
                "riskThreat": [
                  {
                    "code": "C01.00.00",
                    "label": "Gêne à la circulation",
                    "freetext": "risque lié aux voitures"
                  },
                  {
                    "code": "C01.01.00",
                    "label": "Second riskThreat",
                    "freetext": "champ libre"
                  }
                ],
                "victims": {
                  "count": "SEVERAL",
                  "mainVictim": "ADULT",
                  "freetext": "Deuxième victime présente saignements legers aux mains et genoux"
                }
              },
              "location": {
                "locID": "111fb03a-6fd9-41e0-8e81-990c45188887",
                "locLabel": "Lycée Pierre de Coubertin - 12 rue de l'Amitié 77288 Melun, Musée Bossuet - Accès 2 - 77048 Saint-Albray",
                "name": "Lycée Pierre de Coubertin",
                "detailedAddress": {
                  "complete": "9 Bd du Montparnasse",
                  "number": "9, 4bis, PK10, ...",
                  "wayName": {
                    "complete": "Boulevard du Montparnasse",
                    "type": "Boulevard",
                    "name": "du Montparnasse"
                  }
                },
                "city": {
                  "name": "Lille",
                  "inseeCode": "59350",
                  "detail": "Quartier Melun Nord, Lhomme, ..."
                },
                "access": {
                  "floor": "RDC, 1, 2, ...",
                  "roomNumber": "A16, 37, 104, ...",
                  "interphone": "Dupont",
                  "accessCode": [
                    "1234A",
                    "4321B"
                  ],
                  "elevator": "C3",
                  "buildingName": "Batiment B, Batiment Maunoury",
                  "entrance": "Zone Sud, Porte 1, ...",
                  "entity": "Infirmerie, service finance, service cardiologie, ..."
                },
                "geometry": {
                  "obsDatime": "2022-09-27T08:23:34+02:00",
                  "point": {
                    "coord": {
                      "lat": 48.866667,
                      "lon": 2.333333,
                      "height": 120,
                      "heading": 96,
                      "speed": 34,
                      "precision": "ADDRESS"
                    },
                    "sysCoord": "EPSG-4326"
                  },
                  "sketch": "None"
                },
                "externalInfo": [
                  {
                    "freetext": "BAN",
                    "type": "MANUAL",
                    "uri": "id987"
                  }
                ],
                "country": "FR",
                "freetext": "Clé derrière le pot de fleur"
              },
              "initialAlert": {
                "id": "SGO050-20230605-AL0123",
                "reception": "2022-09-27T08:21:06+02:00",
                "reporting": "STANDARD",
                "freetext": "Déclenchement téléalarme, voisine sur les liens",
                "caller": {
                  "callerContact": {
                    "type": "PHNADD",
                    "detail": "0671830530"
                  },
                  "callbackContact": {
                    "type": "PHNADD",
                    "detail": "0671830530"
                  },
                  "language": "FR",
                  "freetext": "Père",
                  "detailedName": {
                    "complete": "Jean Dupont",
                    "lastName": "Dupont",
                    "firstName": "Jean"
                  }
                },
                "alertSource": {
                  "channel": "Personne",
                  "type": "PHNADD",
                  "detail": "0671830530"
                },
                "location": {
                  "locID": "111fb03a-6fd9-41e0-8e81-990c45188887",
                  "name": "Lycée Pierre de Coubertin",
                  "country": "FR"
                },
                "qualification": {
                  "whatsHappen": {
                    "code": "C07.13.02",
                    "label": "Rodéo automobile",
                    "freetext": "None"
                  }
                },
                "callTaker": {
                  "organization": "FR:Administration:44:samu44:crra:regulationN3",
                  "controlRoom": "CGA, CGO 21, CRRA 44, ...",
                  "role": "ARM",
                  "calltakerContact": {
                    "type": "PHNADD",
                    "detail": "0671830530"
                  },
                  "calltakerId": "id1234"
                },
                "attachment": [
                  {
                    "description": "photo, carte, ...",
                    "mimeType": "PDF, XML, JPEG, ...",
                    "size": 1235,
                    "URI": "https://hub.esante.gouv.fr/resourceExample",
                    "derefURI": "None",
                    "digest": "None"
                  }
                ]
              },
              "additionalInformation": {
                "customMap": [
                  {
                    "key": "neighborhood",
                    "label": "Quartier",
                    "value": "LYON 2e arrondissement",
                    "freetext": "Précision sur le quartier d'intervention"
                  }
                ]
              },
              "freetext": "None"
            }
          }
        }
      }
    }
  ]
}

=== ansforge/SAMU-Hub-Modeles/src/main/resources/sample/valid/GEO-POS/GEO-POS.json
{
  "distributionID": "fr.health.hub_2608323d-507d-4cbf-bf74-52007f8124ea",
  "senderID": "fr.health.hub",
  "dateTimeSent": "2022-07-25T10:04:34+01:00",
  "dateTimeExpires": "2072-07-25T10:04:34+01:00",
  "distributionStatus": "Actual",
  "distributionKind": "Report",
  "descriptor": {
    "language": "fr-FR",
    "explicitAddress": {
      "explicitAddressScheme": "hubex",
      "explicitAddressValue": "fr.health.samuA"
    }
  },
  "content": [
    {
      "jsonContent": {
        "embeddedJsonContent": {
          "message": {
            "messageId": "fr.health.samuA_2608323d-507d-4cbf-bf74-52007f8124ea",
            "sender": {
              "name": "samuA",
              "URI": "hubex:fr.health.samuA"
            },
            "sentAt": "2022-07-25T10:04:34+01:00",
            "kind": "Report",
            "status": "Actual",
            "recipient": [
              {
                "name": "samuB",
                "URI": "hubex:fr.health.samuB"
              }
            ],
            "geoPos": {
              "positionUpdate": [
                {
                  "id": "76_45101#SMUR1#",
                  "datetime": "2024-01-27T08:44:00+02:00",
                  "receptionDatetime": "2024-01-27T08:45:00+02:00",
                  "coord": [
                    {
                      "lat": 49.464944,
                      "lon": 1.097341
                    }
                  ],
                  "move": "STATIQUE",
                  "engineOn": false,
                  "status": "DISPONIBLE"
                },
                {
                  "id": "76_45102#SMUR2#",
                  "datetime": "2024-01-27T08:43:00+02:00",
                  "receptionDatetime": "2024-01-27T08:45:00+02:00",
                  "coord": [
                    {
                      "lat": 49.428421,
                      "lon": 1.086735
                    }
                  ],
                  "move": "STATIQUE",
                  "engineOn": true,
                  "status": "INDISPONIBLE",
                  "engagedStatus": "ARRIVEE_LIEU"
                },
                {
                  "id": "76_45104#SMUR4#",
                  "datetime": "2024-01-27T08:46:00+02:00",
                  "receptionDatetime": "2024-01-27T08:48:00+02:00",
                  "coord": [
                    {
                      "lat": 49.448681,
                      "lon": 1.072659
                    }
                  ],
                  "move": "MOBILE",
                  "engineOn": false,
                  "status": "INDISPONIBLE"
                }
              ]
            }
          }
        }
      }
    }
  ]
}

=== ansforge/SAMU-Hub-Modeles/src/main/resources/sample/valid/EMSI-DC/EMSI-DC.json
{
  "distributionID": "fr.health.samuA_2608323d-507d-4cbf-bf74-52007f8124ea",
  "senderID": "fr.health.samuA",
  "dateTimeSent": "2022-07-25T10:04:34+01:00",
  "dateTimeExpires": "2072-07-25T10:04:34+01:00",
  "distributionStatus": "Actual",
  "distributionKind": "Report",
  "descriptor": {
    "language": "fr-FR",
    "explicitAddress": {
      "explicitAddressScheme": "hubex",
      "explicitAddressValue": "fr.health.samuB"
    }
  },
  "content": [
    {
      "jsonContent": {
        "embeddedJsonContent": {
          "message": {
            "CONTEXT": {
              "ID": "d350c9d2-9d76-4568-b0b7-a747ffadc949",
              "MODE": "ACTUAL",
              "MSGTYPE": "UPDATE",
              "CREATION": "2022-09-27T08:25:54+02:00",
              "LINK": [
                {
                  "ID": "samuA:CA126B445579GD4A67AV",
                  "LINK_ROLE": "ADDSTO"
                }
              ],
              "LEVEL": "OPR",
              "SECLASS": "RESTRC",
              "FREETEXT": "Contexte de grand incendie \u00e0 Nantes",
              "ORIGIN": {
                "ORG_ID": "samuA",
                "USER_ID": "samuA:crra:poste1234",
                "NAME": "Samu A"
              },
              "EXTERNAL_INFO": [
                {}
              ]
            },
            "EVENT": {
              "ID": "samuA:CA126B445579GD4A67AV",
              "NAME": "Grand incendie Nantes",
              "MAIN_EVENT_ID": "samuA:CA126B445579GD4A67AV",
              "ETYPE": {
                "CATEGORY": [
                  "FIR"
                ],
                "ACTOR": [
                  "PPL"
                ],
                "LOCTYPE": [
                  "FLAM"
                ],
                "ENV": "/CDIS/RIOT"
              },
              "SOURCE": "COMFOR",
              "SCALE": "3",
              "CERTAINTY": 95,
              "DECL_DATIME": "2022-09-27T08:24:50+02:00",
              "OCC_DATIME": "2022-09-27T08:20:50+02:00",
              "OBS_DATIME": "2022-09-27T08:26:00+02:00",
              "STATUS": "IPR",
              "RISK_ASSESMENT": "STABLE",
              "REFERENCE": [
                {
                  "ORG_ID": "samuC",
                  "OTHER_EVENT_ID": [
                    "samuC:DB326B5RC279GD4A67ZY"
                  ]
                }
              ],
              "CASUALTIES": [
                {
                  "CONTEXT": "REQ_ACTION",
                  "DATIME": "2022-09-27T08:00:00+02:00",
                  "DECONT": 0,
                  "TRIAGERED": 0,
                  "TRIAGEYELLOW": 1,
                  "TRIAGEGREEN": 0,
                  "TRIAGEBLACK": 0,
                  "MISSING": 0
                }
              ],
              "EVAC": [
                {
                  "DATIME": "2022-09-27T10:00:00+02:00",
                  "DISPLACED": 0,
                  "EVACUATED": 1
                }
              ],
              "EGEO": [
                {
                  "DATIME": "2022-09-27T08:26:00+02:00",
                  "TYPE": "FLAME",
                  "WEATHER": [
                    "/HUM/RAIN"
                  ],
                  "FREETEXT": "Un peu de pluie vers 8h",
                  "POSITION": {
                    "LOC_ID": "111fb03a-6fd9-41e0-8e81-990c45188887",
                    "NAME": "Lyc\u00e9e Pierre de Coubertin",
                    "TYPE": "POINT",
                    "HEIGHT_ROLE": "MIN",
                    "COORDSYS": "EPSG-4326",
                    "COORD": [
                      {
                        "LAT": 47.221866,
                        "LONG": -1.575807,
                        "HEIGHT": 1
                      }
                    ],
                    "ADDRESS": [
                      "Nantes centre ville"
                    ]
                  }
                }
              ],
              "CAUSE": "ACC",
              "FREETEXT": "Maison sur le c\u00f4t\u00e9 droit de la route"
            },
            "MISSION": [
              {
                "TYPE": "/SAV/ASC",
                "FREETEXT": "Besoin d'un grand v\u00e9hicule car patients \u00e0 prendre en charge volumineux. Ne pas utiliser les gyrophares en approche",
                "ID": "ABC1YU3454",
                "ORG_ID": "sis44",
                "NAME": "#DEMANDE_CONCOURS#CARENCE#Z.01.00.00#",
                "STATUS": "IPR",
                "START_TIME": "2022-09-27T08:21:00+02:00",
                "END_TIME": "2022-09-27T10:21:00+02:00",
                "RESOURCE_ID": [
                  "Non trait\u00e9"
                ],
                "PARENT_MISSION_ID": [
                  "Non trait\u00e9"
                ],
                "CHILD_MISSION_ID": [
                  "Non trait\u00e9"
                ],
                "MAIN_MISSION_ID": "Non trait\u00e9",
                "POSITION": {
                  "LOC_ID": "abcd-hg6T-HSG5-67AA",
                  "NAME": "Lyc\u00e9e Pierre de Coubertin",
                  "TYPE": "POINT",
                  "HEIGHT_ROLE": "MIN",
                  "COORDSYS": "EPSG-4326",
                  "COORD": [
                    {
                      "LAT": 47.221866,
                      "LONG": -1.575807,
                      "HEIGHT": 1
                    }
                  ],
                  "ADDRESS": [
                    "None"
                  ]
                },
                "PRIORITY": "4"
              }
            ]
          }
        }
      }
    }
  ]
}
