=== ansforge/SAMU-Hub-Modeles/src/main/resources/json-schema/RS-URL.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "classpath:/json-schema/schema#",
    "x-id": "RS-URL.schema.json#",
    "version": "26.06.15",
    "example": "example.json#",
    "type": "object",
    "title": "documentLink",
    "required": [
        "caseId",
        "document"
    ],
    "properties": {
        "caseId": {
            "type": "string",
            "title": "Identifiant partagé du dossier de régulation médicale (DRM)",
            "x-health-only": false,
            "x-cols": 6,
            "example": "example.json#/caseId",
            "description": "Identifiant partagé du dossier, généré une seule fois par le système du partenaire qui recoit la primo-demande de secours (créateur du dossier). \nIl est valorisé comme suit lors de sa création : \n{pays}.{domaine}.{organisation}.{senderCaseId}\n\nIl doit pouvoir être généré de façon décentralisée et ne présenter aucune ambiguïté.\n Il doit être unique dans l'ensemble des systèmes : le numéro de dossier fourni par celui qui génère l'identifiant partagé doit donc être un numéro unique dans son système.",
            "pattern": "^([a-zA-Z0-9_-]+\\.?){4,10}$"
        },
        "patientId": {
            "type": "string",
            "title": "Identifiant partagé du patient",
            "x-health-only": false,
            "x-cols": 6,
            "example": "example.json#/patientId",
            "description": "Indique l'identifiant partagé du patient auquel les documents sont rattachés",
            "pattern": "^([a-zA-Z0-9_-]+\\.){3,8}patient(\\.[a-zA-Z0-9_-]+){1,2}$"
        },
        "code": {
            "type": "string",
            "title": "Code d'accès au bilan",
            "x-health-only": false,
            "x-cols": 6,
            "example": "example.json#/code",
            "description": "Code unitaire par bilan qui permet à l'utilisateur qui reçoit ce lien d'ouvrir le bilan lorsque celui ci ne nécessite pas une connexion nominative mais un code bilan "
        },
        "document": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/document"
            },
            "minItems": 1
        }
    },
    "definitions": {
        "document": {
            "type": "object",
            "title": "Documents",
            "x-display": "expansion-panels",
            "x-health-only": false,
            "required": [
                "url"
            ],
            "properties": {
                "documentType": {
                    "type": "string",
                    "title": "Type de document",
                    "x-health-only": false,
                    "x-cols": 6,
                    "example": "example.json#/document/0/documentType",
                    "description": "Informe l'utilisateur du type de document que le lien URL permet d'ouvrir"
                },
                "url": {
                    "type": "string",
                    "title": "URL",
                    "x-health-only": false,
                    "x-cols": 6,
                    "example": "example.json#/document/0/url",
                    "description": "URL qui permet à l'utilisateur du LRM d'ouvrir le type de document précisé dans le champ précédent"
                }
            },
            "additionalProperties": false,
            "example": "example.json#/document/0"
        }
    },
    "additionalProperties": false
}

=== ansforge/SAMU-Hub-Modeles/csv_parser/out/RS-URL/RS-URL.example.json
{
    "caseId": "fr.health.samu440.DRFR15440241550012",
    "patientId": "fr.health.samu690.patient.P23AZ59\nfr.health.samu690.patient.DRFR15690242370035.1",
    "code": "5f5h8s9",
    "document": [
        {
            "documentType": "Photo, ECG, bilan pdf, prescription, carte d'identit√©",
            "url": "https://hub.esante.gouv.fr/"
        }
    ]
}
